### ISSUE TITLE
specific chunks to hide or show option

### ISSUE THREAD

**Issue by JulienGAMartin** [bblodfon/rtemps#2]
Hi
for the bookdown_lite, it seems that all the code chunks are either hidden or shown by default (when changing  `window.initializeCodeFolding("show" === "hide")`. Is it possible to show all chunks except for a few? 
So if by default all chunks are hidden can I specify an option to show a specific chunk by default similarly to the `class.source = 'fold-show'` option in html_document ?

**Comment by edzer** [comment]
I also have this question!

**Comment by bblodfon** [comment]
@edzer It has been implemented in the newest release: use the chunk option `class.source = 'fold-show'` and it works, the corresponding chunk will be shown.
