### ISSUE TITLE
Reusing codefolding in other project (license)

### ISSUE THREAD

**Issue by Lauler** [bblodfon/rtemps#3]
Hi!

Great templates. Because of the license for the repository, I was wondering whether it is alright to reuse only some specific parts of this package in my own bookdown project with proper attribution? Specifically, I'm looking to use only the code folding [hide_code.html](https://github.com/bblodfon/rtemps/blob/master/docs/bookdown-lite/hide_code.html) implementation.

Stackoverflow answers are CC-BY-SA, so in a sense technically your adaptation of that code folding example should fall under same license. However, thought it polite to check with you first.

**Comment by bblodfon** [comment]
Hi Lauler,

Thanks for asking about this! I would think that the [MIT license](https://github.com/bblodfon/rtemps/blob/master/LICENSE.md) in the repository covers (positively) this case, no? Can you share the Stackoverflow answers you found specific to this just out of curiosity?

**Comment by Lauler** [comment]
Ah, I was a bit too quick and careless, clicking "View License" on the right side menu lead to this link: https://github.com/bblodfon/rtemps/blob/master/LICENSE . I missed that there was a LICENCE.md . 

That license certainly covers the case!

I found your package through this link: https://stackoverflow.com/questions/45360998/code-folding-in-bookdown , and assumed your solution drew some inspiration from the accepted answer.
