### ISSUE TITLE
How to use with bookdown::bs4_book:

### ISSUE THREAD

**Issue by Williamson-Nicole** [bblodfon/rtemps#4]
Hi! 

I tried using your hide_code.html for bookdown::bs4_book: and it **almost** works. The buttons are created and they do expand the code chunk on click but only for a second then it collapses and disappears again. I think maybe its because its not compatible with bootstraps 4? I don't know JavaScript so I don't know how to fix this issue. 

Thanks!

**Comment by bblodfon** [comment]
Hi Nicole! Well the code folding was never intended to "play" with `bs4_book` as this format came later (only with `gitbook`).

Nowadays, Quarto is the way to go - it supports [code folding](https://quarto.org/docs/output-formats/html-code.html#folding-code) automatically, well-integrated with Rstudio, so I would suggest to have a look at that.

**Comment by Williamson-Nicole** [comment]
Oh wow I hadn't heard of this yet, this is great thank you!
